import type { EnvelopeSpec } from './envelope-types.js';

const ID = { id: 'string' } as const;

/**
 * The complete napplet wire surface: every `domain.action` discriminant across
 * NAP domains, with its direction and (for outbound) required fields.
 */
export const ENVELOPE_SPECS: Record<string, EnvelopeSpec> = {
  // Optional NAP-SHELL environment, independent of other domains.
  'shell.ready': { dir: 'out' },
  'shell.init': { dir: 'in', fields: { capabilities: 'object', services: 'array' } },
  // ── relay ────────────────────────────────────────────────────────────────
  'relay.subscribe': { dir: 'out', fields: { ...ID, subId: 'string', filters: 'array' } },
  'relay.close': { dir: 'out', fields: { ...ID, subId: 'string' } },
  'relay.publish': { dir: 'out', fields: { ...ID, event: 'object' } },
  'relay.publishEncrypted': { dir: 'out', fields: { ...ID, event: 'object', recipient: 'string' } },
  'relay.query': { dir: 'out', fields: { ...ID, filters: 'array' } },
  'relay.event': { dir: 'in' },
  'relay.eose': { dir: 'in' },
  'relay.closed': { dir: 'in' },
  'relay.publish.result': { dir: 'in' },
  'relay.publishEncrypted.result': { dir: 'in' },
  'relay.query.result': { dir: 'in' },

  // ── identity ─────────────────────────────────────────────────────────────
  'identity.getPublicKey': { dir: 'out', fields: { ...ID } },
  'identity.getRelays': { dir: 'out', fields: { ...ID } },
  'identity.getProfile': { dir: 'out', fields: { ...ID } },
  'identity.getFollows': { dir: 'out', fields: { ...ID } },
  'identity.getList': { dir: 'out', fields: { ...ID, listType: 'string' } },
  'identity.getZaps': { dir: 'out', fields: { ...ID } },
  'identity.getMutes': { dir: 'out', fields: { ...ID } },
  'identity.getBlocked': { dir: 'out', fields: { ...ID } },
  'identity.getBadges': { dir: 'out', fields: { ...ID } },
  'identity.changed': { dir: 'in' },
  'identity.getPublicKey.result': { dir: 'in' },
  'identity.getRelays.result': { dir: 'in' },
  'identity.getProfile.result': { dir: 'in' },
  'identity.getFollows.result': { dir: 'in' },
  'identity.getList.result': { dir: 'in' },
  'identity.getZaps.result': { dir: 'in' },
  'identity.getMutes.result': { dir: 'in' },
  'identity.getBlocked.result': { dir: 'in' },
  'identity.getBadges.result': { dir: 'in' },

  // ── storage ──────────────────────────────────────────────────────────────
  'storage.get': { dir: 'out', fields: { ...ID, key: 'string' } },
  'storage.set': { dir: 'out', fields: { ...ID, key: 'string', value: 'string' } },
  'storage.remove': { dir: 'out', fields: { ...ID, key: 'string' } },
  'storage.keys': { dir: 'out', fields: { ...ID } },
  'storage.get.result': { dir: 'in' },
  'storage.set.result': { dir: 'in' },
  'storage.remove.result': { dir: 'in' },
  'storage.keys.result': { dir: 'in' },

  // ── inc (inter-napplet communication) ─────────────────────────────────────
  'inc.emit': { dir: 'out', fields: { topic: 'string' }, forbiddenFields: ['sender'] },
  'inc.subscribe': { dir: 'out', fields: { ...ID, topic: 'string' } },
  'inc.unsubscribe': { dir: 'out', fields: { topic: 'string' } },
  'inc.channel.open': { dir: 'out', fields: { ...ID, target: 'string' } },
  'inc.channel.emit': { dir: 'out', fields: { channelId: 'string' } },
  'inc.channel.broadcast': { dir: 'out' },
  'inc.channel.list': { dir: 'out', fields: { ...ID } },
  'inc.channel.close': { dir: 'out', fields: { channelId: 'string' } },
  'inc.subscribe.result': { dir: 'in' },
  'inc.event': { dir: 'in', fields: { topic: 'string', sender: 'string' } },
  'inc.channel.open.result': { dir: 'in' },
  'inc.channel.opened': { dir: 'in', fields: { channelId: 'string', peer: 'string' } },
  'inc.channel.event': { dir: 'in' },
  'inc.channel.list.result': { dir: 'in' },
  'inc.channel.closed': { dir: 'in' },

  // ── theme ────────────────────────────────────────────────────────────────
  'theme.get': { dir: 'out', fields: { ...ID } },
  'theme.get.result': { dir: 'in' },
  'theme.changed': { dir: 'in' },

  // ── keys ─────────────────────────────────────────────────────────────────
  'keys.forward': {
    dir: 'out',
    fields: { key: 'string', code: 'string', ctrl: 'boolean', alt: 'boolean', shift: 'boolean', meta: 'boolean' },
  },
  'keys.registerAction': { dir: 'out', fields: { ...ID, action: 'object' } },
  'keys.unregisterAction': { dir: 'out', fields: { actionId: 'string' } },
  'keys.registerAction.result': { dir: 'in' },
  'keys.bindings': { dir: 'in' },
  'keys.action': { dir: 'in' },

  // ── media ────────────────────────────────────────────────────────────────
  'media.session.create': { dir: 'out', fields: { ...ID, owner: 'object' } },
  'media.session.update': { dir: 'out', fields: { sessionId: 'string', metadata: 'object' } },
  'media.session.destroy': { dir: 'out', fields: { sessionId: 'string' } },
  'media.state': { dir: 'out', fields: { sessionId: 'string', status: 'string' } },
  'media.capabilities': { dir: 'out', fields: { sessionId: 'string', actions: 'array' } },
  'media.session.create.result': { dir: 'in' },
  'media.command': { dir: 'in' },
  'media.controls': { dir: 'in' },

  // ── notify ───────────────────────────────────────────────────────────────
  'notify.send': { dir: 'out', fields: { ...ID, title: 'string' } },
  'notify.dismiss': { dir: 'out', fields: { notificationId: 'string' } },
  'notify.badge': { dir: 'out', fields: { count: 'number' } },
  'notify.channel.register': { dir: 'out', fields: { channelId: 'string', label: 'string' } },
  'notify.permission.request': { dir: 'out', fields: { ...ID } },
  'notify.send.result': { dir: 'in' },
  'notify.permission.result': { dir: 'in' },
  'notify.action': { dir: 'in' },
  'notify.clicked': { dir: 'in' },
  'notify.dismissed': { dir: 'in' },
  'notify.controls': { dir: 'in' },

  // ── config ───────────────────────────────────────────────────────────────
  'config.registerSchema': { dir: 'out', fields: { ...ID, schema: 'object' } },
  'config.get': { dir: 'out', fields: { ...ID } },
  'config.subscribe': { dir: 'out' },
  'config.unsubscribe': { dir: 'out' },
  'config.openSettings': { dir: 'out' },
  'config.registerSchema.result': { dir: 'in' },
  'config.values': { dir: 'in' },
  'config.schemaError': { dir: 'in' },

  // ── resource ─────────────────────────────────────────────────────────────
  'resource.info': { dir: 'out', fields: { ...ID } },
  'resource.bytes': { dir: 'out', fields: { ...ID, url: 'string' } },
  'resource.bytesMany': { dir: 'out', fields: { ...ID, requests: 'array' } },
  'resource.cancel': { dir: 'out', fields: { ...ID } },
  'resource.info.result': { dir: 'in' },
  'resource.info.error': { dir: 'in' },
  'resource.bytes.result': { dir: 'in' },
  'resource.bytes.error': { dir: 'in' },
  'resource.bytesMany.result': { dir: 'in' },
  'resource.bytesMany.error': { dir: 'in' },

  // ── cvm ──────────────────────────────────────────────────────────────────
  'cvm.discover': { dir: 'out', fields: { ...ID } },
  'cvm.request': { dir: 'out', fields: { ...ID, server: 'object', message: 'object' } },
  'cvm.close': { dir: 'out', fields: { ...ID, server: 'object' } },
  'cvm.registry.list': { dir: 'out', fields: { ...ID } },
  'cvm.registry.has': { dir: 'out', fields: { ...ID, family: 'string' } },
  'cvm.registry.describe': { dir: 'out', fields: { ...ID, family: 'string' } },
  'cvm.registry.call': { dir: 'out', fields: { ...ID, family: 'string', tool: 'string' } },
  'cvm.discover.result': { dir: 'in' },
  'cvm.request.result': { dir: 'in' },
  'cvm.close.result': { dir: 'in' },
  'cvm.event': { dir: 'in' },
  'cvm.registry.list.result': { dir: 'in' },
  'cvm.registry.has.result': { dir: 'in' },
  'cvm.registry.describe.result': { dir: 'in' },
  'cvm.registry.call.result': { dir: 'in' },

  // ── outbox ───────────────────────────────────────────────────────────────
  'outbox.getEvent': { dir: 'out', fields: { ...ID, eventId: 'string' } },
  'outbox.query': { dir: 'out', fields: { ...ID, filters: 'present' } },
  'outbox.subscribe': { dir: 'out', fields: { ...ID, subId: 'string', filters: 'present' } },
  'outbox.close': { dir: 'out', fields: { ...ID, subId: 'string' } },
  'outbox.publish': { dir: 'out', fields: { ...ID, event: 'object' } },
  'outbox.resolveRelays': { dir: 'out', fields: { ...ID, target: 'present' } },
  'outbox.getEvent.result': { dir: 'in' },
  'outbox.query.result': { dir: 'in' },
  'outbox.event': { dir: 'in' },
  'outbox.closed': { dir: 'in' },
  'outbox.publish.result': { dir: 'in' },
  'outbox.resolveRelays.result': { dir: 'in' },

  // ── upload ───────────────────────────────────────────────────────────────
  'upload.info': { dir: 'out', fields: { ...ID } },
  'upload.upload': { dir: 'out', fields: { ...ID, request: 'object' } },
  'upload.status': { dir: 'out', fields: { ...ID, uploadId: 'string' } },
  'upload.info.result': { dir: 'in' },
  'upload.upload.result': { dir: 'in' },
  'upload.status.result': { dir: 'in' },
  'upload.status.changed': { dir: 'in' },

  // ── intent ───────────────────────────────────────────────────────────────
  'intent.invoke': { dir: 'out', fields: { ...ID, request: 'object' } },
  'intent.available': { dir: 'out', fields: { ...ID, archetype: 'string' } },
  'intent.handlers': { dir: 'out', fields: { ...ID } },
  'intent.invoke.result': { dir: 'in', fields: { ...ID, result: 'object' } },
  'intent.available.result': { dir: 'in' },
  'intent.handlers.result': { dir: 'in' },
  'intent.deliver': { dir: 'in', fields: { delivery: 'object' } },
  'intent.changed': { dir: 'in' },

  // ── ble ──────────────────────────────────────────────────────────────────
  'ble.open': { dir: 'out', fields: { ...ID, request: 'object' } },
  'ble.services': { dir: 'out', fields: { ...ID, sessionId: 'string' } },
  'ble.read': { dir: 'out', fields: { ...ID, sessionId: 'string', target: 'object' } },
  'ble.write': { dir: 'out', fields: { ...ID, sessionId: 'string', target: 'object', data: 'array' } },
  'ble.subscribe': { dir: 'out', fields: { ...ID, sessionId: 'string', target: 'object' } },
  'ble.unsubscribe': { dir: 'out', fields: { ...ID, sessionId: 'string', target: 'object' } },
  'ble.close': { dir: 'out', fields: { ...ID, sessionId: 'string' } },
  'ble.open.result': { dir: 'in' },
  'ble.services.result': { dir: 'in' },
  'ble.read.result': { dir: 'in' },
  'ble.write.result': { dir: 'in' },
  'ble.subscribe.result': { dir: 'in' },
  'ble.unsubscribe.result': { dir: 'in' },
  'ble.close.result': { dir: 'in' },
  'ble.event': { dir: 'in' },

  // ── common ───────────────────────────────────────────────────────────────
  'common.encodeNip19': { dir: 'out', fields: { ...ID, input: 'object' } },
  'common.decodeNip19': { dir: 'out', fields: { ...ID, value: 'string' } },
  'common.getProfile': { dir: 'out', fields: { ...ID, target: 'string' } },
  'common.follows': { dir: 'out', fields: { ...ID } },
  'common.follow': { dir: 'out', fields: { ...ID, pubkeys: 'array' } },
  'common.unfollow': { dir: 'out', fields: { ...ID, pubkeys: 'array' } },
  'common.react': { dir: 'out', fields: { ...ID, targetEventId: 'string', reaction: 'string' } },
  'common.report': { dir: 'out', fields: { ...ID, target: 'object', reason: 'string', text: 'string' } },
  'common.encodeNip19.result': { dir: 'in' },
  'common.decodeNip19.result': { dir: 'in' },
  'common.getProfile.result': { dir: 'in' },
  'common.follows.result': { dir: 'in' },
  'common.follow.result': { dir: 'in' },
  'common.unfollow.result': { dir: 'in' },
  'common.react.result': { dir: 'in' },
  'common.report.result': { dir: 'in' },

  // ── webrtc ────────────────────────────────────────────────────────────────
  'webrtc.open': { dir: 'out', fields: { ...ID, request: 'object' } },
  'webrtc.send': { dir: 'out', fields: { ...ID, sessionId: 'string', payload: 'present' } },
  'webrtc.close': { dir: 'out', fields: { ...ID, sessionId: 'string' } },
  'webrtc.open.result': { dir: 'in' },
  'webrtc.send.result': { dir: 'in' },
  'webrtc.close.result': { dir: 'in' },
  'webrtc.event': { dir: 'in' },
  // ── link ─────────────────────────────────────────────────────────────────
  'link.open': { dir: 'out', fields: { ...ID, url: 'string' } },
  'link.open.result': { dir: 'in' },
  // ── count ────────────────────────────────────────────────────────────────
  'count.query': { dir: 'out', fields: { ...ID, filters: 'array' } },
  'count.query.result': { dir: 'in' },
  // ── lists ────────────────────────────────────────────────────────────────
  'lists.supported': { dir: 'out', fields: { ...ID } },
  'lists.add': { dir: 'out', fields: { ...ID, list: 'object', items: 'array' } },
  'lists.remove': { dir: 'out', fields: { ...ID, list: 'object', items: 'array' } },
  'lists.supported.result': { dir: 'in' },
  'lists.add.result': { dir: 'in' },
  'lists.remove.result': { dir: 'in' },
  // ── serial ───────────────────────────────────────────────────────────────
  'serial.open': { dir: 'out', fields: { ...ID, request: 'object' } },
  'serial.write': { dir: 'out', fields: { ...ID, sessionId: 'string', data: 'array' } },
  'serial.close': { dir: 'out', fields: { ...ID, sessionId: 'string' } },
  'serial.open.result': { dir: 'in' },
  'serial.write.result': { dir: 'in' },
  'serial.close.result': { dir: 'in' },
  'serial.event': { dir: 'in' },

  // ── fs ───────────────────────────────────────────────────────────────────
  'fs.info': { dir: 'out', fields: { ...ID } },
  'fs.pickFile': { dir: 'out', fields: { ...ID } },
  'fs.pickFiles': { dir: 'out', fields: { ...ID } },
  'fs.pickDirectory': { dir: 'out', fields: { ...ID } },
  'fs.pickSaveFile': { dir: 'out', fields: { ...ID } },
  'fs.stat': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.list': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.read': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.write': { dir: 'out', fields: { ...ID, path: 'string', data: 'string' } },
  'fs.mkdir': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.remove': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.move': { dir: 'out', fields: { ...ID, fromPath: 'string', toPath: 'string' } },
  'fs.watch': { dir: 'out', fields: { ...ID, path: 'string' } },
  'fs.unwatch': { dir: 'out', fields: { ...ID, watchId: 'string' } },
  'fs.info.result': { dir: 'in' },
  'fs.pickFile.result': { dir: 'in' },
  'fs.pickFiles.result': { dir: 'in' },
  'fs.pickDirectory.result': { dir: 'in' },
  'fs.pickSaveFile.result': { dir: 'in' },
  'fs.stat.result': { dir: 'in' },
  'fs.list.result': { dir: 'in' },
  'fs.read.result': { dir: 'in' },
  'fs.write.result': { dir: 'in' },
  'fs.mkdir.result': { dir: 'in' },
  'fs.remove.result': { dir: 'in' },
  'fs.move.result': { dir: 'in' },
  'fs.watch.result': { dir: 'in' },
  'fs.unwatch.result': { dir: 'in' },
  'fs.changed': { dir: 'in' },

  // ── dm ───────────────────────────────────────────────────────────────────
  'dm.status': { dir: 'out', fields: { ...ID } },
  'dm.conversations': { dir: 'out', fields: { ...ID } },
  'dm.messages': { dir: 'out', fields: { ...ID, conversationId: 'string' } },
  'dm.send': { dir: 'out', fields: { ...ID, recipients: 'array', content: 'string' } },
  'dm.subscribe': { dir: 'out', fields: { ...ID } },
  'dm.unsubscribe': { dir: 'out', fields: { ...ID, subscriptionId: 'string' } },
  'dm.status.result': { dir: 'in' },
  'dm.conversations.result': { dir: 'in' },
  'dm.messages.result': { dir: 'in' },
  'dm.send.result': { dir: 'in' },
  'dm.subscribe.result': { dir: 'in' },
  'dm.unsubscribe.result': { dir: 'in' },
  'dm.message': { dir: 'in' },
};
