import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'relay/index': 'src/relay/index.ts',
    'relay/types': 'src/relay/types.ts',
    'relay/shim': 'src/relay/shim.ts',
    'relay/sdk': 'src/relay/sdk.ts',
    'storage/index': 'src/storage/index.ts',
    'storage/types': 'src/storage/types.ts',
    'storage/shim': 'src/storage/shim.ts',
    'storage/sdk': 'src/storage/sdk.ts',
    'ifc/index': 'src/ifc/index.ts',
    'ifc/types': 'src/ifc/types.ts',
    'ifc/shim': 'src/ifc/shim.ts',
    'ifc/sdk': 'src/ifc/sdk.ts',
    'keys/index': 'src/keys/index.ts',
    'keys/types': 'src/keys/types.ts',
    'keys/shim': 'src/keys/shim.ts',
    'keys/sdk': 'src/keys/sdk.ts',
    'theme/index': 'src/theme/index.ts',
    'theme/types': 'src/theme/types.ts',
    'media/index': 'src/media/index.ts',
    'media/types': 'src/media/types.ts',
    'media/shim': 'src/media/shim.ts',
    'media/sdk': 'src/media/sdk.ts',
    'notify/index': 'src/notify/index.ts',
    'notify/types': 'src/notify/types.ts',
    'notify/shim': 'src/notify/shim.ts',
    'notify/sdk': 'src/notify/sdk.ts',
    'identity/index': 'src/identity/index.ts',
    'identity/types': 'src/identity/types.ts',
    'identity/shim': 'src/identity/shim.ts',
    'identity/sdk': 'src/identity/sdk.ts',
    'config/index': 'src/config/index.ts',
    'config/types': 'src/config/types.ts',
    'config/shim': 'src/config/shim.ts',
    'config/sdk': 'src/config/sdk.ts',
    'resource/index': 'src/resource/index.ts',
    'resource/types': 'src/resource/types.ts',
    'resource/shim': 'src/resource/shim.ts',
    'resource/sdk': 'src/resource/sdk.ts',
    'connect/index': 'src/connect/index.ts',
    'connect/types': 'src/connect/types.ts',
    'connect/shim': 'src/connect/shim.ts',
    'connect/sdk': 'src/connect/sdk.ts',
    'class/index': 'src/class/index.ts',
    'class/types': 'src/class/types.ts',
    'class/shim': 'src/class/shim.ts',
    'class/sdk': 'src/class/sdk.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
});
