/**
 * @napplet/core -- Shared protocol types, constants, and topic definitions.
 *
 * This package is the single source of truth for all protocol-level
 * definitions in the napplet ecosystem. All other @napplet/* packages
 * import their protocol types and constants from here.
 *
 * Zero dependencies. No DOM or browser APIs.
 *
 * @example
 * ```ts
 * import {
 *   type NostrEvent, type NostrFilter,
 *   type NappletMessage, type NapDomain,
 *   type NapHandler, type NapDispatch,
 *   NAP_DOMAINS, TOPICS,
 *   createDispatch, registerNap, dispatch, getRegisteredDomains,
 * } from '@napplet/core';
 * ```
 *
 * @packageDocumentation
 */

export type {
  NappletMessage,
  NapDomain,
} from './envelope.js';
export { NAP_DOMAINS } from './envelope.js';

export type { NapHandler, NapDispatch } from './dispatch.js';
export { createDispatch, registerNap, dispatch, getRegisteredDomains } from './dispatch.js';

export type {
  NostrEvent,
  NostrFilter,
  Subscription,
  EventTemplate,
  MediaPlaybackOwner,
  MediaSourceRef,
  MediaMetadata,
  MediaState,
  MediaAction,
  MediaSessionCreate,
  MediaSessionResult,
  McpMessage,
  McpTool,
  McpContentBlock,
  McpToolResult,
  McpResource,
  McpTextResourceContents,
  McpBlobResourceContents,
  McpResourceContent,
  CvmServerRef,
  CvmDiscoverQuery,
  CvmServer,
  CvmRequestOptions,
  OutboxStrategy,
  OutboxEventOptions,
  OutboxQueryOptions,
  OutboxSubscribeOptions,
  OutboxPublishOptions,
  OutboxTarget,
  OutboxRelayPlan,
  OutboxEventResult,
  OutboxResult,
  OutboxPublishResult,
  OutboxSubscription,
  NostrTag,
  UploadRail,
  UploadState,
  UploadRequest,
  UploadResult,
  UploadStatus,
  IntentHandlerPreference,
  IntentBehavior,
  IntentRequest,
  IntentContract,
  IntentCandidate,
  IntentAvailability,
  IntentResult,
  BleUuid,
  BleSessionState,
  BleOpenRequest,
  BleDeviceFilter,
  BleManufacturerDataFilter,
  BleServiceDataFilter,
  BleOpenResult,
  BleSession,
  BleDeviceInfo,
  BleService,
  BleCharacteristic,
  BleCharacteristicProperties,
  BleAttribute,
  BleWriteOptions,
  BleEvent,
  BleStateEvent,
  BleNotificationEvent,
  BleClosedEvent,
  BleApi,
  WebrtcScope,
  WebrtcDirectScope,
  WebrtcRoomScope,
  WebrtcOpenRequest,
  WebrtcOpenResult,
  WebrtcState,
  WebrtcSession,
  WebrtcEvent,
  WebrtcStateEvent,
  WebrtcPeerEvent,
  WebrtcMessageEvent,
  WebrtcClosedEvent,
  WebrtcApi,
  LinkOpenErrorCode,
  LinkOpenOptions,
  LinkOpenResult,
  LinkOpenStatus,
  ListErrorCode,
  ListItem,
  ListItemType,
  ListItemVisibility,
  ListMutationResult,
  ListOptions,
  ListRef,
  ListSupport,
  CommonActionResult,
  CommonEventReportTarget,
  CommonFollowsResult,
  CommonHexPubkey,
  CommonNip19DecodeResult,
  CommonNip19EncodeInput,
  CommonNip19EncodeResult,
  CommonNip19Type,
  CommonNostrEventId,
  CommonProfileData,
  CommonProfileResult,
  CommonProfileTarget,
  CommonPubkeyReportTarget,
  CommonReaction,
  CommonReportReason,
  CommonReportTarget,
  DmHexPubkey,
  DmTimestamp,
  DmStatus,
  DmConversationQuery,
  DmPeer,
  DmConversation,
  DmConversationPage,
  DmMessageQuery,
  DmMessageStatus,
  DmMessage,
  DmMessagePage,
  DmSendRequest,
  DmSendResult,
  DmSubscribeRequest,
  DmSubscription,
  DmOk,
  SerialState,
  SerialPortFilter,
  SerialOpenOptions,
  SerialOpenRequest,
  SerialPortInfo,
  SerialSession,
  SerialOpenResult,
  SerialEvent,
  NappletGlobal,
  NappletInstanceStorage,
  ResourceApi,
  ResourceErrorCode,
  ResourceBytesOkItem,
  ResourceBytesErrorItem,
  ResourceBytesItem,
} from './types.js';

export { TOPICS } from './topics.js';
export type { TopicKey, TopicValue } from './topics.js';

export type { CloneMode, PostMessageTarget } from './boundary.js';
export {
  sendEnvelope,
  toCloneableSnapshot,
  setCloneMode,
  getCloneMode,
  clearCloneWarnings,
} from './boundary.js';
